# Generated by Django 3.0.14 on 2022-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyalUsers',
            fields=[
                ('user_name', models.CharField(db_column='User_name', max_length=50)),
                ('user_surname', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_phone', models.IntegerField(unique=True)),
                ('user_email', models.CharField(max_length=150, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'loyal_users',
                'managed': False,
            },
        ),
    ]
