# Generated by Django 3.0.14 on 2022-10-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base',
        ),
    ]
