# Generated by Django 3.0.14 on 2022-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyal_users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_from', models.CharField(blank=True, max_length=150, null=True)),
                ('area_to', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'buses',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LoyalUsers',
        ),
    ]
